export { Header } from "./header"
export { Hero } from "./hero"
export { Industries } from "./industries"
export { Features } from "./features"
export { Partners } from "./partners"
export { CTA } from "./cta"
export { Footer } from "./footer"
